
const opportunityList = [
    {
        name: 'Smart India Hackathon',
        description: 'Smart India Hackathon is a nationwide initiative to provide students with a platform to solve some of the pressing problems we face in our daily lives, and thus inculcate a culture of product innovation and a mindset of problem-solving. The first three editions SIH2017, SIH2018 and SIH2019 proved to be extremely successful in promoting innovation out-of-the-box thinking in young minds, especially engineering students from across India. Smart India Hackathon is a nationwide initiative to provide students with a platform to solve some of the pressing problems we face in our daily lives, and thus inculcate a culture of product innovation and a mindset of problem-solving. The first three editions SIH2017, SIH2018 and SIH2019 proved to be extremely successful in promoting innovation out-of-the-box thinking in young minds, especially engineering students from across India. Smart India Hackathon is a nationwide initiative to provide students with a platform to solve some of the pressing problems we face in our daily'
    },
    {
        name: 'Smart India Hackathon',
        description: 'Smart India Hackathon is a nationwide initiative to provide students with a platform to solve some of the pressing problems we face in our daily lives, and thus inculcate a culture of product innovation and a mindset of problem-solving. The first three editions SIH2017, SIH2018 and SIH2019 proved to be extremely successful in promoting innovation out-of-the-box thinking in young minds, especially engineering students from across India. Smart India Hackathon is a nationwide initiative to provide students with a platform to solve some of the pressing problems we face in our daily lives, and thus inculcate a culture of product innovation and a mindset of problem-solving. The first three editions SIH2017, SIH2018 and SIH2019 proved to be extremely successful in promoting innovation out-of-the-box thinking in young minds, especially engineering students from across India. Smart India Hackathon is a nationwide initiative to provide students with a platform to solve some of the pressing problems we face in our daily'
    },
    {
        name: 'Smart India Hackathon',
        description: 'Smart India Hackathon is a nationwide initiative to provide students with a platform to solve some of the pressing problems we face in our daily lives, and thus inculcate a culture of product innovation and a mindset of problem-solving. The first three editions SIH2017, SIH2018 and SIH2019 proved to be extremely successful in promoting innovation out-of-the-box thinking in young minds, especially engineering students from across India. Smart India Hackathon is a nationwide initiative to provide students with a platform to solve some of the pressing problems we face in our daily lives, and thus inculcate a culture of product innovation and a mindset of problem-solving. The first three editions SIH2017, SIH2018 and SIH2019 proved to be extremely successful in promoting innovation out-of-the-box thinking in young minds, especially engineering students from across India. Smart India Hackathon is a nationwide initiative to provide students with a platform to solve some of the pressing problems we face in our daily'
    },
]

export default opportunityList